HomeWork/Models/AccountBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        public int Categoryyy { get; set; }
        public int Amounttt { get; set; }
        public System.DateTime Dateee { get; set; }
        public string Remarkkk { get; set; }
    }
}

HomeWork/Models/CommonModels/CategoryCommonModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeWork.Models.CommonModels
{
    public enum CategoryCommonModels
    {
        支出 = 0,
        收入 = 1
    }
}

HomeWork/Models/HomeWorkModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkillTreeHomeworkEntities : DbContext
    {
        public SkillTreeHomeworkEntities()
            : base("name=SkillTreeHomeworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBook> AccountBook { get; set; }
    }
}

HomeWork/Models/HomeWorkModels.Designer.cs
// 已啟用模型 'E:\電腦教學\ASP.NET MVC\SkillTree_3Day\作業\HomeWork\HomeWork\Models\HomeWorkModels.edmx' 的 T4 程式碼產生。
// 若要啟用舊版程式碼產生，請將 [程式碼產生策略] 設計工具屬性的值
//變更為 [舊版 ObjectContext]。當模型在設計工具中開啟時，這個屬性便可
//以在 [屬性] 視窗中使用。

// 如果尚未產生任何內容和實體類型，可能是因為您建立了空的模型，但
//尚未選擇要使用的 Entity Framework 版本。若要為您的模型產生內容類別和
//實體類型，請在設計工具中開啟模型，以滑鼠右鍵按一下設計工具介面並
//選取 [從資料庫更新模型]、[由模型產生資料庫] 或 [加入程式碼產生
//項目]。

HomeWork/Models/HomeWorkModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

HomeWork/Models/ViewModels/MoneyTemplateViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using HomeWork.Models.CommonModels;
using HomeWork.Validation;

namespace HomeWork.Models.ViewModels
{
    public class MoneyTemplateViewModels
    {
        [Required(ErrorMessage = "類別 必須輸入!")]
        [Display(Name = "類別")]
        public CategoryCommonModels Category { get; set; }

        [Required(ErrorMessage = "金額 必須輸入!")]
        [Range(0, 32767, ErrorMessage = "只能輸入正整數!")]
        [Display(Name = "金額")]
        public int Money { get; set; }

        //[Required(ErrorMessage = "日期 必須輸入!")]
        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "日期不得大於今天!")]
        [Display(Name = "日期")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "備註 必須輸入!")]
        [StringLength(100, ErrorMessage = "最多輸入100個字元!")]
        [Display(Name = "備註")]
        public string Description { get; set; }
    }
}

HomeWork/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeWork.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HomeWork/Controllers/MoneyTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HomeWork.Models;
using HomeWork.Models.ViewModels;
using HomeWork.Service;

namespace HomeWork.Controllers
{
    public class MoneyTemplateController : Controller
    {
        SkillTreeHomeworkEntities db = new SkillTreeHomeworkEntities();
        MoneyTemplateService moneyTemplateService = new MoneyTemplateService();

        // GET: MoneyTemplate
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(MoneyTemplateViewModels model)
        {
            //判斷模型繫結是否錯誤，或者有商業邏輯上是否錯誤
            if (ModelState.IsValid)
            {
                AccountBook accountBooks = new AccountBook();
                accountBooks.Id= Guid.NewGuid();
                accountBooks.Categoryyy = model.Category.ToString() == "支出" ? 0 : 1;
                accountBooks.Amounttt = model.Money;
                accountBooks.Dateee = model.Date;
                accountBooks.Remarkkk = model.Description;
                db.AccountBook.Add(accountBooks);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult ItemList()
        {
            var model = moneyTemplateService.GetItemList();

            return View(model);
        }
    }
}

HomeWork/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HomeWork/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HomeWork/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HomeWork/Views/MoneyTemplate/Index.cshtml
@model HomeWork.Models.ViewModels.MoneyTemplateViewModels

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container body-content">

        <div class="well">
            <form class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="col-sm-2 text-right">
                        @Html.LabelFor(model => model.category, new { @class = "control-label" })

                    </div>
                    <div class="col-sm-10">
                        @Html.EnumDropDownListFor(model => model.category, "請選擇", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 text-right">
                        @Html.LabelFor(model => model.money, new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.money, new { @class = "form-control", @placeholder = "金額" })
                        @Html.ValidationMessageFor(model => model.money, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 text-right">
                        @Html.LabelFor(model => model.date, new { @class = "control-label" })                        
                    </div>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.date, new { @class = "form-control", @placeholder = "日期" })
                        @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 text-right">
                        @Html.LabelFor(model => model.description, new { @class = "control-label" })
                    </div>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-8 col-sm-4">
                        <button type="submit" class="btn btn-default">送出</button>
                    </div>
                </div>
            </form>
        </div>

        @Html.Action("ItemList", "MoneyTemplate")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWork/Views/MoneyTemplate/ItemList.cshtml
@model IEnumerable<HomeWork.Models.ViewModels.MoneyTemplateViewModels>

@{
    Layout = null;
    var i = 0;
}

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <thead class="bg-primary">
                <tr>
                    <th width="10%">#</th>
                    <th width="30%">@Html.DisplayNameFor(model => model.category)</th>
                    <th width="30%">@Html.DisplayNameFor(model => model.date)</th>
                    <th width="30%">@Html.DisplayNameFor(model => model.money)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="10%">@(++i)</td>
                        <td width="30%">
                            @{
                                if (item.category == 0)
                                {
                                    <p class="text-danger">@Html.DisplayFor(modelItem => item.category)</p>
                                }
                                else
                                {
                                    <p class="text-primary">@Html.DisplayFor(modelItem => item.category)</p>
                                }
                            }
                        </td>
                        <td width="30%">
                            @(item.date.ToString("yyyy-MM-dd"))
                        </td>
                        <td width="30%">
                            @(item.money.ToString("#,0"))
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

HomeWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的記帳本</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("我的記帳本", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="#">SkillTree</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>